name       : pysolfc-cardsets
version    : '2.0'
release    : 3
source     :
    - https://sourceforge.net/projects/pysolfc/files/PySolFC-Cardsets/PySolFC-Cardsets-2.0/PySolFC-Cardsets-2.0.tar.bz2/download : c388d6360191b3b7e463d84e5a64260c4e3ed36e791a85227d7e8923f3f47ca7
license    : GPL-3.0
component  : desktop.library
summary    : PySolFC Extra Cardsets
description: |
    PySolFC Extra Cardsets
install    : |
    rm -r cardset-{2000,hexadeck,standard,crystal-mahjongg,kintengu,tuxedo,dashavatara-ganjifa,matrix,vienna-2k,dondorf,mughal-ganjifa,gnome-mahjongg-1,oxymoron}
    mkdir -p $installdir/usr/share/PySolFC/
    cp -r * $installdir/usr/share/PySolFC/
