name       : pysolfc-cardsets
version    : 2.0
release    : 1
source     :
    - http://internode.dl.sourceforge.net/project/pysolfc/PySolFC-Cardsets/PySolFC-Cardsets-2.0/PySolFC-Cardsets-2.0.tar.bz2 : c388d6360191b3b7e463d84e5a64260c4e3ed36e791a85227d7e8923f3f47ca7
license    : GPL-3.0
summary    : PySolFC Extra Cardsets
description: |
    PySolFC Extra Cardsets
rundeps    :
    - pysolfc
builddeps  :
setup      : |
build      : |
install    : |
    rm -r cardset-2000
    rm -r cardset-hexadeck
    rm -r cardset-standard
    rm -r cardset-crystal-mahjongg
    rm -r cardset-kintengu
    rm -r cardset-tuxedo
    rm -r cardset-dashavatara-ganjifa
    rm -r cardset-matrix
    rm -r cardset-vienna-2k
    rm -r cardset-dondorf
    rm -r cardset-mughal-ganjifa
    rm -r cardset-gnome-mahjongg-1
    rm -r cardset-oxymoron
    mkdir -p %installroot%/usr/share/PySolFC/
    mv * %installroot%/usr/share/PySolFC/
